// src/components/solid/FuriganaComponent.tsx
/** @jsxImportSource solid-js */
import type { Furigana } from "curtiz-japanese-nlp";
import type { Component } from "solid-js";
interface Props {
  furigana: Furigana[];
}
export const FuriganaComponent: Component<Props> = ({ furigana }) => (
  <>
    {furigana.map((f) =>
      typeof f === "string" ? (
        f
      ) : (
        <ruby>
          {f.ruby}
          <rt>{f.rt}</rt>
        </ruby>
      )
    )}
  </>
);

// src/components/Furigana.tsx
import { Fragment, type FunctionalComponent } from "preact";
import type { Furigana as FuriganaType } from "curtiz-japanese-nlp";

interface Props {
  furigana: FuriganaType[];
}
export const Furigana: FunctionalComponent<Props> = ({ furigana }) => {
  return (
    <span>
      {furigana.map((f) => (
        <Fragment>
          {typeof f === "string" ? (
            f
          ) : (
            <ruby>
              {f.ruby}
              <rt>{f.rt}</rt>
            </ruby>
          )}
        </Fragment>
      ))}
    </span>
  );
};
